export interface EmployeeRecord {
  recordId: string
  id: string
  zk: string
  saber: string
  finalCode: string
  fullName: string
  lastName: string
  firstName: string
  gender: string
  kind: string
  contract: string
  department: string
  service: string
  job: string
  hiredAt: string
  payType: string
  signed: string
  status: string
  inactiveFrom: string
}

export interface EmployeeDraft extends EmployeeRecord {
  lockedRecordId?: string
}

export interface DetailSelection {
  title: string
  note: string
  totalCount: number
  items: EmployeeRecord[]
}

export type EmployeeEditorMode = 'closed' | 'create' | 'edit'

export interface EmployeeFieldConfig {
  name: keyof EmployeeDraft
  label: string
  type: 'text' | 'select'
  options?: string[]
  autoGenerated?: boolean
}
