export const defaultHrData = {
  sourceFile: 'Base RH en ligne',
  snapshotDate: '30/07/2026',
  totals: {
    employees: 158,
    active: 109,
    stc: 49,
    signedContracts: 113,
    unsignedContracts: 45,
  },
  activeMix: {
    moi: 46,
    mod: 63,
    women: 71,
    men: 38,
  },
  alerts: [
    {
      label: 'Actifs sans contrat signe',
      value: 4,
      note: 'A regulariser en priorite.',
    },
    {
      label: 'Actifs sans type de paie',
      value: 33,
      note: 'Champs a completer pour fiabiliser la paie.',
    },
    {
      label: 'Fiches sans matricule final',
      value: 12,
      note: 'Verifier les doublons et la codification finale.',
    },
  ],
  activeDepartments: [
    { label: 'Production', value: 71 },
    { label: 'RH', value: 13 },
    { label: 'Technique', value: 11 },
    { label: "Qualite'", value: 9 },
    { label: 'Direction', value: 3 },
    { label: 'Logistique', value: 2 },
  ],
  activeServices: [
    { label: 'MET', value: 27 },
    { label: 'ASSEM', value: 22 },
    { label: 'INJ', value: 16 },
    { label: "Qualite' Prod", value: 8 },
    { label: 'Gardiennage', value: 7 },
    { label: 'Maintenance', value: 6 },
    { label: 'SERIG', value: 5 },
    { label: 'Nettoyage', value: 4 },
  ],
  contracts: [
    { label: 'CDI', value: 58 },
    { label: 'CDD', value: 36 },
    { label: 'CIVP', value: 6 },
    { label: 'KARAMA', value: 5 },
    { label: 'PATENTE', value: 4 },
  ],
  payTypes: [
    { label: 'Horaire', value: 52 },
    { label: 'Mensuel', value: 24 },
    { label: 'Non renseigne', value: 33 },
  ],
  recentHires: [
    {
      lastName: 'EL AYEB',
      firstName: 'NAOURES',
      date: '14/07/2026',
      department: 'RH',
      service: 'Administratif',
      contract: 'KARAMA',
    },
    {
      lastName: 'BRAHEM',
      firstName: 'WISSEM',
      date: '13/07/2026',
      department: 'RH',
      service: 'Gardiennage',
      contract: 'CDI',
    },
    {
      lastName: 'WERFELLI',
      firstName: 'OUSSEMA',
      date: '07/07/2026',
      department: 'Logistique',
      service: 'Supply Chain',
      contract: 'KARAMA',
    },
    {
      lastName: 'NASRALLI',
      firstName: 'THOURAYA',
      date: '03/07/2026',
      department: 'Production',
      service: 'MET',
      contract: 'CDI',
    },
    {
      lastName: 'LABBEN',
      firstName: 'FARAH',
      date: '01/07/2026',
      department: 'Production',
      service: 'MET',
      contract: 'CDI',
    },
    {
      lastName: 'HASNI',
      firstName: 'ZAINEB',
      date: '01/07/2026',
      department: 'Production',
      service: 'MET',
      contract: 'CDI',
    },
  ],
};
